### ISSUE TITLE
Incompatible with Phpstorm 2022.2.1

### ISSUE THREAD

**Issue by demwarlord** [kookob/plugin#10]
Doesn't work

![](https://i.imgur.com/TBRlX5h.png)
![](https://i.imgur.com/Xp6H2C8.png)
![](https://i.imgur.com/tCkHMWJ.png)
![](https://i.imgur.com/acTLRJC.png)

**Comment by kookob** [comment]
Have you ever restarted the IDE?
Or try to reactivate the plugin.

**Comment by demwarlord** [comment]
Yes, restarted and reinstalled many times.

**Comment by kookob** [comment]
I have tested that it is compatible, Is it because the plugin is not activated? If you do not buy it, you can try to buy one?
Coupon: BY6R6-QHJXV-56NA4-DPWLM-T9V4M

**Comment by demwarlord** [comment]
Yes, after buying it works. I just wanted to try it before buying.
