### ISSUE TITLE
 Icon not visible in dark mode

### ISSUE THREAD

**Issue by miguelmhs** [kookob/plugin#12]
Please, fix an issue in dark mode not showing icon (you can see in the attached images),
![infinyta_–_ctrl_señal py_Administrator_2022-11-13_11-12-23](https://user-images.githubusercontent.com/24484413/201518887-0c1e1baa-23ad-4893-a813-f36275010870.png)
![2022-11-13_11-12-57](https://user-images.githubusercontent.com/24484413/201518890-5e8cf9fa-b645-42f7-8f38-4daff1378aae.png)

**Comment by kookob** [comment]
Got it, thanks!

**Comment by kookob** [comment]
@miguelmhs I update a new logo for this plugin new version. I hope you like it
