### ISSUE TITLE
Regex Tool is not compatible with latest release of IntelliJ 2022.3

### ISSUE THREAD

**Issue by jmatias** [kookob/plugin#13]
![image](https://user-images.githubusercontent.com/1302269/205426457-6ab9dd97-ffb9-42d6-b7cb-2ebe69e13841.png)

![image](https://user-images.githubusercontent.com/1302269/205426548-19b39937-33a0-4dfd-8919-fedaa12cb987.png)

![image](https://user-images.githubusercontent.com/1302269/205426819-a8aa2607-a82e-43de-bfaa-2ae60bd8249d.png)

**Comment by kookob** [comment]
I am sorry, I will update new version asap, and will be approved by JetBrains in next week. (2~3 days)
Thank you for your feedback.

**Comment by kookob** [comment]
The new version is valid now. Thanks.

**Comment by jmatias** [comment]
thank you, happy to help
