### ISSUE TITLE
CRON generator works inappropriate

### ISSUE THREAD

**Issue by IVoyt** [kookob/plugin#14]
The ending number stands for execution day and 1 means Monday while plugin renders Sunday

<img width="334" alt="image" src="https://user-images.githubusercontent.com/10925772/235654682-d1326a75-3a28-46c8-9b82-da3ef13e7888.png">

**Comment by kookob** [comment]
The ending number 1-7 means SUN-SAT, 
The first day of the week is Sunday, not Monday. and 1 is used to represent Sunday here.

**Comment by IVoyt** [comment]
Well that is confusing. Cron valid values for day of week are 0-6
(Sun-Sat). Where did you take 1-7 is correct?



Вт, 2 мая 2023 г. в 14:44, ob ***@***.***>:

**Comment by kookob** [comment]
Sorry, There may be some error here.
For linux and Spring, the allowable values are 0-7, where 0 and 7 represent Sunday.
For Quartz, the allowable values are 1-7, where 1 represents Sunday.
My Toolset plugin use Quartz implement. 
So incompatible with all here.
A better approach is to directly specify the day of the week.
`0 0 1 ? * Mon`
https://stackoverflow.com/questions/18919151/crontab-day-of-the-week-syntax
https://en.wikipedia.org/wiki/Cron

**Comment by IVoyt** [comment]
Got it, thank you for the explanation

вт, 2 мая 2023 г. в 15:25, ob ***@***.***>:

**Comment by kookob** [comment]
I apologize for the delay in responding to this issue. I want to inform you that the new version of the toolset plugin now supports the Unix cron expression. Thank you.

**Comment by IVoyt** [comment]
Hi. Thank you, I've noticed that in one of the recent changelogs :)

пн, 4 дек. 2023 г. в 13:41, ob ***@***.***>:
