### ISSUE TITLE
toolset 每次唤起都会卡顿一下

### ISSUE THREAD

**Issue by ZHOUXING1997** [kookob/plugin#18]

**Comment by kookob** [comment]
是第一次才会，还是每次都会？
大概有多久？如果是第一次在一两秒内的，属于正常，因为要初始化所有Tab工具。
如果想提高点速度，可以把不常用的Tab功能隐藏起来，这样就不会初始化（右上角配置里面）
如果是每次都会的话，帮忙贴下，IDE和插件的版本号，我看能不能重现。

**Comment by ZHOUXING1997** [comment]
那应该是初始化吧




周星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kookob/plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月25日(星期一) 中午11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kookob/plugin] toolset 每次唤起都会卡顿一下 (Issue #18)





 
是第一次才会，还是每次都会？
 大概有多久？如果每一次是一两秒内的，属于正常，因为要初始化所有Tab工具。
 如果想提高点速度，可以把不常用的Tab功能隐藏起来，这样就不会初始化（右上角配置里面）
 如果是每次都会的话，帮忙贴下，IDE和插件的版本号，我看能不能重现。

**Comment by kookob** [comment]
嗯，IDE整个运行期间，插件只会初始化一次
