### ISSUE TITLE
Requires 2021.1.1 but the  latest EAP of Intellj is 2021.1

### ISSUE THREAD

**Issue by dicklieber** [kookob/plugin#3]
Requires 2021.1.1 but the  latest EAP of Intellj is 2021.1
can't run

**Comment by kookob** [comment]
@dicklieber which plugin? I will upload a new version.

**Comment by dicklieber** [comment]
Regex tool

**Comment by kookob** [comment]
Got it, I will update it.
And you can try my another plugin "[Toolset](https://plugins.jetbrains.com/plugin/14384-toolset)", It contains more features there(include Regex Tool).
And send you a 100%OFF discount code
L3LPX-7XLNE-FZR7F-4QFHK-MYB7U
Thank you for your support!

**Comment by Ocramsretep** [comment]
I get the message `Regex Tool plugin incompatible with this version`.
Is there no version for the current IDEA version?

My IntelliJ IDEA version:
IntelliJ IDEA 2020.3.3 (Community Edition)
Build #IC-203.7717.56, built on March 15, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 4
Non-Bundled Plugins: CVS, com.intellij.marketplace, com.obroom.plugin.regextool, org.jetbrains.kotlin, PlantUML integration

My Regex Tool version:
![image](https://user-images.githubusercontent.com/78689564/112016826-5a515180-8b2d-11eb-96a2-e2941f387284.png)

**Comment by kookob** [comment]
@dicklieber 
@Ocramsretep 
Thank you. I have uploaded the new fix version, and it will be updated after it is approved.
And you can try the toolset plugin: https://plugins.jetbrains.com/plugin/14384-toolset
Toolset plugin contains the regex tool all features.
Below are two 100%OFF discount codes that you can use
K495Z-S8H4V-5WCN9-GN4XR-FNC97
3PEZB-TL3FT-JRADV-HQNS7-SUVK5
