### ISSUE TITLE
cron表达式方言问题

### ISSUE THREAD

**Issue by xianzheTM** [kookob/plugin#4]
插件没有说明cron表达式识别的是哪种方言.以该[网站](https://tool.lu/crontab/)的三种实例来说,只有quartz的识别了.
k8s中cronjob使用的5位cron表达式方言更不能识别.
希望能够拓展识别的方言类型.

**Comment by kookob** [comment]
@xianzheTM 默认是Java 6个参数的那种，像cronjob 5位的参数，只不过把秒级别的去年，其他表达式基本上是相通的。
