### ISSUE TITLE
IntelliJ IDEA Ultimate 2021.3.1无法正常使用 

### ISSUE THREAD

**Issue by MrLiu94** [kookob/plugin#5]
![image](https://user-images.githubusercontent.com/40285071/149871701-b53fd007-05a6-4850-a07b-db776410b954.png)
已经按照要求在yml文件中进行了配置 但是restore SQL后仍然是空白 用的版本是2021.9.1

**Comment by kookob** [comment]
插件界面不太对啊，IDE重启了吗

**Comment by MrLiu94** [comment]
> 

![image](https://user-images.githubusercontent.com/40285071/149890894-09b71af7-da2d-4c6c-95d0-79916aab43ff.png)
重启后点开插件会报不兼容错误--

**Comment by kookob** [comment]
试下本地授权的版本看看。
跟你的m1应该是没有关系。
https://www.yuque.com/kookob/plugin/local

**Comment by MrLiu94** [comment]
> 试下本地授权的版本看看。 跟你的m1应该是没有关系。 https://www.yuque.com/kookob/plugin/local

下载下来只有22b 然后安装失败 我的在线版购买邮箱是liusj49@outlook.com 麻烦能发我一份么？

**Comment by kookob** [comment]
http://plugin.obroom.com/public/jar/jpa-sql-2021.9.1.jar
地址没更新，用这个试下

**Comment by MrLiu94** [comment]
> http://plugin.obroom.com/public/jar/jpa-sql-2021.9.1.jar

![image](https://user-images.githubusercontent.com/40285071/149903249-fe138090-261b-419f-af71-d45e5a4c522c.png)
还是不行。。

**Comment by kookob** [comment]
那可能要等下个版本再修复了，你看下能否找官方退款，后台取消下购买订单。实在抱歉了。

**Comment by MrLiu94** [comment]
> 那可能要等下个版本再修复了，你看下能否找官方退款，后台取消下购买订单。实在抱歉了。

哦哦 好的 后面等修复了再支持
