### ISSUE TITLE
Toolset plugin does not work the latest EAP of Intellj

### ISSUE THREAD

**Issue by fados** [kookob/plugin#8]
Toolset plugin does not work the latest EAP of Intellj

```
IntelliJ IDEA 2022.2 EAP (Ultimate Edition)
Build #IU-222.2680.4, built on May 25, 2022
Runtime version: 17.0.3+7-b463.3 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
```
![Screenshot 2022-06-01 at 15 51 10](https://user-images.githubusercontent.com/19396764/171434850-48ae81eb-3ed0-4393-84ab-5373285ca863.png)

**Comment by AX-LLaidley** [comment]
+1 to this. I have the same exact issue. Any ETA on a compatible version?

**Comment by defiob** [comment]
Sorry, Within a week.

**Comment by kookob** [comment]
Sorry, Within a week.

**Comment by kookob** [comment]
New version:
https://plugins.jetbrains.com/plugin/14384-toolset/versions/stable/181915
